# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/prefer-default-export: 0
  no-plusplus: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always